spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 5
    lease-expiration-duration-in-seconds: 5
  client: 
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry:  false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  # renewalPercentThreshold: 0.85
  # enableSelfPreservation: false